### ISSUE TITLE
Update ceph libvirt secret fails when cluster have multiple users

### ISSUE THREAD

**Issue by fao89** [openstack-k8s-operators/nova-operator#424] opened 2023-06-26 19:57 UTC
```
[root@standalone ~]# ls /etc/ceph
ceph.client.admin.keyring      ceph.client.radosgw.keyring
ceph.client.openstack.keyring  ceph.conf
[root@standalone ~]# ls /etc/ceph/${cluster}.client.*.keyring | grep -v admin | awk -F . '{print $3}'
openstack
radosgw
[root@standalone ~]# echo ${CLUSTER_USER_MAP[$cluster]}
openstack radosgw
[root@standalone ~]# keyring=$(awk '$1 == "key" {print $3}' /etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$cluster]}.keyring)
awk: fatal: cannot open file `/etc/ceph/ceph.client.openstack' for reading: No such file or directory
```
https://github.com/openstack-k8s-operators/data-plane-adoption/pull/58#issuecomment-1608105300
`/etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$cluster]}.keyring` is expanded to `/etc/ceph/ceph.client.openstack radosgw.keyring`  which breaks the script

**Comment by fultonj** [comment] 2023-06-26 20:31
This line of awk:
```
keyring=$(awk '$1 == "key" {print $3}' /etc/ceph/${cluster}.client.${CLUSTER_USER_MAP[$cluster]}.keyring)
```
In this playbook https://github.com/openstack-k8s-operators/nova-operator/blob/main/playbooks/deploy-libvirt.yaml#L126

Needs to be updated so that it deals with each item inside the `${CLUSTER_USER_MAP[$cluster]}` list.

**Comment by SeanMooney** [comment] 2023-06-26 21:30
Yep this is a know issue. We have an issue for it already and it's on my to-do list. Between my new laptop and mainly jira I lost 6 weeks to unplanned work but this was originally planned for q2

**Comment by SeanMooney** [comment] 2023-06-26 21:31
The is a duplicate of https://github.com/openstack-k8s-operators/nova-operator/issues/315

**Comment by SeanMooney** [comment] 2023-06-27 10:37
lets continue to use https://github.com/openstack-k8s-operators/nova-operator/issues/315 for this

**Closed by SeanMooney** 2023-06-27 10:37 UTC
